site_name: Zhiyuan Chen
site_url: https://zyc.ai
site_author: Zhiyuan Chen
site_description: The website of Zhiyuan Chen
copyright: All rights reserved &copy; Zhiyuan Chen 2017-2020

repo_name: Zhiyuan Chen
repo_url: https://github.com/ZhiyuanChen

nav:
  - zyc.ai: index.md
  # - 联想研究院:
  #   - 联想研究院实习总结: lenovo_research.md
  - 文档:
    - 设计模式: document/design_pattern.md
    - JetBrains使用指南: document/jetbrains.md
    - PyTorch分布式: document/torch.distributed.md
  - 统计:
    - 概率论: stat/probability.md
  - 优化:
    - 优化: optimisation/introduction.md
    - 仿射与凸: optimisation/affine_convex.md
    - 球与锥: optimisation/ball_cone.md
    - 超平面、半空间与多面体: optimisation/hyperplane_halfspace_polyhedra.md
    - 对偶锥与广义不等式: optimisation/dual_cone_generalized_inequality.md
    - 凸凹: optimisation/convex_concave.md
  #- 机器学习:
  #  - 统计: ml/statistics.md
  - 计算机视觉:
    - SimCLR: cv/ssl/SimCLR.md
  #  - SiamRPN: cv/siamrpn.md
  # - 生物医学影像:
  #   - 超声: bmi/ultrasound.md
  # - 算法:
  #   - 算法导论: algorithm/introduction.md
  #   - 复杂度: algorithm/complexity.md
  #   - 树: algorithm/tree.md
  #   - 递推方程: algorithm/recurrence_relation.md
  - Kubernetes:
    - 导论: k8s/introduction.md
    - 组件: k8s/component.md
    - 安装: k8s/installation.md
    - Pods: k8s/pods.md
    - Deployments: k8s/deployments.md
  - Docker:
    - 导论: docker/introduction.md
    - 安装: docker/installation.md
    - 命令行接口: docker/command_line_interface.md
    - Dockerfile: docker/dockerfile.md
  # - CNTK:
  #   - 导论: cntk/introduction.md
  #   - 200: cntk/200.md
  - C++核心指南:
    - 原文: cppcg/CppCoreGuidelines.md
    - 摘要: cppcg/abstract.md
  - 速食食品:
    - 速食食品の评测: instant_food/introduction.md
  - 随笔:
    - 二〇一九年 六月 十日: sketch/20190610.md
    - 二〇一九年 十一月 八日: sketch/20191108.md
    - 二〇二〇年 四月 四日: sketch/20200404.md
    - 二〇二〇年 十月 六日: sketch/20201006.md
  - 关于:
    - Zhiyuan Chen: about.md
    - 捐赠: about/donate.md
    - 贡献: about/contribute.md
    - 最终用户许可协议: about/eula.md
    - 隐私声明: about/privacy.md
    - 评论政策: about/comment.md
    - GPLv3: about/license.md

theme:
  name: material
  language: 'zh'
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: 'assests/site/logo.png'
  favicon: 'assests/site/logo.png'
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - header.autohide
  font:
    text: 'Helvetica'
    code: 'Cascadia Code'

extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/ZhiyuanChen'
    - icon: fontawesome/brands/gitlab
      link: 'https://gitlab.com/ZhiyuanChen'
    - icon: fontawesome/brands/bitbucket
      link: 'https://bitbucket.org/ZhiyuanChen'
    - icon: fontawesome/solid/paper-plane
      link: mailto:this@zyc.ai
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/zyc.fb
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zyc_ai
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/zyc.ai
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/%E9%99%9F%E5%8E%9F-%E9%99%88-0b473aa9/'
  alternate:
    - name: English
      link: https://zyc.ai/en/
      lang: en
  disqus: 'zycai'
  generator: false
  # version:
  #   method: mike

extra_css:
    #- css/css.css
    #- css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics:
  - 'UA-104387513-1'
  - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - def_list
  - footnotes
  - mdx_math
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "#"

plugins:
  - search:
      prebuild_index: true
  - awesome-pages
  - git-revision-date-localized:
      type: iso_datetime
  - git-committers